Fixed CI

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -2,11 +2,7 @@ name: Node.js CI
 
 on:
   push:
-    branches:
-      - '*'
   pull_request:
-    branches:
-      - '*'
 
 jobs:
   build:
@@ -43,15 +39,20 @@ jobs:
       - name: Create pindie database
         run: mongo --eval "db.getSiblingDB('pindie')"
 
-      - name: Start server
-        run: npm start
-        background: true
+      - name: 'Test server'
+        uses: miguelteixeiraa/action-run-in-background@v1
+        with:
+          script: |
+            npm start
 
-      - name: Wait for server to start
-        run: sleep 10s
-      
-      - name: Send ping request
-        run: curl http://localhost:3000/api/ping
-      
-      - name: Stop server
-        run: npm stop
+          readiness-script: |
+            # check if whatever is it to run, is ready
+            if curl -sSf http://localhost:3000/api/ping > /dev/null; then
+                echo "curl request was successful."
+            else
+                echo "curl request failed."
+                exit 1
+            fi
+
+          shell: bash
+          timeout: 30
